# Preliminaries  

**Overview**  
This section provides the essential survival skills needed before diving into deep learning. It covers how to manipulate and preprocess data, the linear algebra and calculus concepts that underlie neural networks, the use of automatic differentiation, basic probability for reasoning under uncertainty, and how to effectively use documentation. These fundamentals ensure you can follow the technical content of later chapters with confidence.  
<br>  

---


## A. Data Manipulation  

**Recap**  
This section introduces tensors, the core data structure in PyTorch. A tensor is just a container for numbers in one or more dimensions. We can create them, manipulate them with operations, automatically broadcast shapes when combining arrays of different sizes, save memory efficiently, and convert between PyTorch and other Python objects like NumPy.  

**Vocab**  
- **Tensor**: A general container for numbers in 1D (vector), 2D (matrix), or higher dimensions.  
- **Broadcasting**: Expanding smaller arrays automatically to match larger shapes during operations.  

**Notes**  
- Tensors are arrays of numbers: 1D = vector, 2D = matrix, higher = tensor.  
- Tensors support math operations (add, subtract, multiply, divide) applied elementwise.  
- Broadcasting lets smaller tensors expand to match larger shapes automatically.  
- In-place operations (`a.add_(b)`) save memory but overwrite values directly.  
- Tensors can be converted to/from NumPy arrays or Python scalars, sharing memory in the process.  


In [18]:
import torch

# Create a vector and a matrix
v = torch.arange(3)          # [0, 1, 2]
M = torch.ones((3, 3))       # 3x3 of ones

# Broadcasting: vector expands to match matrix shape
result = M + v

# In-place operation: overwrite to save memory
M.add_(v)   # modifies M directly

print("Original vector v:\n", v)
print("\nMatrix M after in-place add with broadcasting:\n", M)
print("\nResult (new tensor, not in-place):\n", result)


Original vector v:
 tensor([0, 1, 2])

Matrix M after in-place add with broadcasting:
 tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

Result (new tensor, not in-place):
 tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])
